import { v4 as uuidv4 } from 'uuid';
import { db } from './database.js';

export function seedDatabase() {
  const data = db.getAll();
  
  if (data.models.length > 0) {
    return;
  }
  
  const now = new Date().toISOString();
  
  const paperIds = [uuidv4(), uuidv4(), uuidv4(), uuidv4(), uuidv4()];
  const paperData = [
    {
      id: paperIds[0],
      type: '双面彩色',
      size: '15cm x 15cm',
      color: '红色/白色',
      quantity: 50,
      lowStockThreshold: 10,
      notes: '标准折纸用纸',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: paperIds[1],
      type: '和纸',
      size: '20cm x 20cm',
      color: '米白色',
      quantity: 20,
      lowStockThreshold: 5,
      notes: '高级和纸，适合复杂模型',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: paperIds[2],
      type: '单面彩色',
      size: '15cm x 15cm',
      color: '蓝色',
      quantity: 5,
      lowStockThreshold: 10,
      notes: '库存不足，需要补充',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: paperIds[3],
      type: '牛皮纸',
      size: '30cm x 30cm',
      color: '棕色',
      quantity: 15,
      lowStockThreshold: 5,
      notes: '适合大型模型',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: paperIds[4],
      type: '锡纸',
      size: '20cm x 20cm',
      color: '银色',
      quantity: 12,
      lowStockThreshold: 5,
      notes: '适合金属质感模型',
      createdAt: now,
      updatedAt: now,
    },
  ];
  
  const modelIds = [uuidv4(), uuidv4(), uuidv4(), uuidv4(), uuidv4()];
  const modelsData = [
    {
      id: modelIds[0],
      name: '千纸鹤',
      designer: '传统',
      category: '鸟类',
      difficulty: '简单',
      recommendedPaperType: '双面彩色',
      recommendedPaperSize: '15cm x 15cm',
      stepCount: 12,
      estimatedTimeMinutes: 5,
      tutorialSource: '传统折纸教程',
      description: '最经典的折纸模型之一，象征和平与希望。简单易学，是折纸入门的最佳选择。',
      images: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: modelIds[1],
      name: '玫瑰',
      designer: '川崎敏和',
      category: '花朵',
      difficulty: '复杂',
      recommendedPaperType: '单面彩色',
      recommendedPaperSize: '20cm x 20cm',
      stepCount: 45,
      estimatedTimeMinutes: 45,
      tutorialSource: '川崎敏和折纸艺术',
      description: '著名的川崎玫瑰，以其逼真的花瓣造型著称。需要一定的折纸基础和耐心。',
      images: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: modelIds[2],
      name: '跳跳蛙',
      designer: '传统',
      category: '动物',
      difficulty: '简单',
      recommendedPaperType: '单面彩色',
      recommendedPaperSize: '15cm x 15cm',
      stepCount: 10,
      estimatedTimeMinutes: 3,
      tutorialSource: '儿童折纸入门',
      description: '经典的儿童折纸，按压尾部可以跳跃。简单有趣，适合初学者。',
      images: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: modelIds[3],
      name: '龙',
      designer: '神谷哲史',
      category: '动物',
      difficulty: '极复杂',
      recommendedPaperType: '和纸',
      recommendedPaperSize: '30cm x 30cm',
      stepCount: 120,
      estimatedTimeMinutes: 180,
      tutorialSource: '神谷哲史作品集',
      description: '神谷哲史的经典龙造型，细节丰富，需要高超的折纸技巧和大量时间。',
      images: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: modelIds[4],
      name: '纸盒',
      designer: '传统',
      category: '盒子',
      difficulty: '中等',
      recommendedPaperType: '双面彩色',
      recommendedPaperSize: '20cm x 20cm',
      stepCount: 20,
      estimatedTimeMinutes: 15,
      tutorialSource: '实用折纸',
      description: '实用的折纸盒子，可以用来收纳小物品。多种变体，简单实用。',
      images: [],
      createdAt: now,
      updatedAt: now,
    },
  ];
  
  const stepsData = [
    {
      id: uuidv4(),
      modelId: modelIds[0],
      stepNumber: 1,
      foldType: '谷折',
      description: '将正方形纸对角折叠，形成三角形。',
      referencePoints: '对齐四个角，确保边缘平整',
      imageUrl: '',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: uuidv4(),
      modelId: modelIds[0],
      stepNumber: 2,
      foldType: '谷折',
      description: '展开后，将另一条对角线也折叠。',
      referencePoints: '形成十字形折痕',
      imageUrl: '',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: uuidv4(),
      modelId: modelIds[0],
      stepNumber: 3,
      foldType: '山折',
      description: '将纸翻过来，沿中线山折。',
      referencePoints: '折痕与对角线交叉',
      imageUrl: '',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: uuidv4(),
      modelId: modelIds[0],
      stepNumber: 4,
      foldType: '沉折',
      description: '沿折痕将纸压平，形成正方形基础形。',
      referencePoints: '四个角汇聚到底部',
      imageUrl: '',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: uuidv4(),
      modelId: modelIds[0],
      stepNumber: 5,
      foldType: '谷折',
      description: '将两侧的边向中心折叠。',
      referencePoints: '对齐中心线',
      imageUrl: '',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: uuidv4(),
      modelId: modelIds[0],
      stepNumber: 6,
      foldType: '谷折',
      description: '顶部向下折叠，然后展开。',
      referencePoints: '形成新的折痕',
      imageUrl: '',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: uuidv4(),
      modelId: modelIds[0],
      stepNumber: 7,
      foldType: '内翻折',
      description: '沿折痕将上部向内翻折，形成鹤的头部。',
      referencePoints: '两侧对称',
      imageUrl: '',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: uuidv4(),
      modelId: modelIds[0],
      stepNumber: 8,
      foldType: '外翻折',
      description: '将末端向外翻折，形成鹤的喙。',
      referencePoints: '小三角向外翻出',
      imageUrl: '',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: uuidv4(),
      modelId: modelIds[0],
      stepNumber: 9,
      foldType: '谷折',
      description: '两侧的翅膀向下折叠。',
      referencePoints: '与身体平行',
      imageUrl: '',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: uuidv4(),
      modelId: modelIds[0],
      stepNumber: 10,
      foldType: '其他',
      description: '轻轻拉开翅膀，使身体鼓起来。',
      referencePoints: '从底部吹气使形状立体',
      imageUrl: '',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: uuidv4(),
      modelId: modelIds[2],
      stepNumber: 1,
      foldType: '谷折',
      description: '将长方形纸上下对折。',
      referencePoints: '对齐长边',
      imageUrl: '',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: uuidv4(),
      modelId: modelIds[2],
      stepNumber: 2,
      foldType: '谷折',
      description: '展开，将两侧向中线折叠。',
      referencePoints: '形成两个三角形',
      imageUrl: '',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: uuidv4(),
      modelId: modelIds[2],
      stepNumber: 3,
      foldType: '谷折',
      description: '上下两端向中心折叠。',
      referencePoints: '边缘对齐',
      imageUrl: '',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: uuidv4(),
      modelId: modelIds[2],
      stepNumber: 4,
      foldType: '其他',
      description: '翻过来，完成基础形。',
      referencePoints: '调整形状',
      imageUrl: '',
      createdAt: now,
      updatedAt: now,
    },
  ];
  
  const foldDates = [
    new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    new Date().toISOString().split('T')[0],
  ];
  
  const foldsData = [
    {
      id: uuidv4(),
      modelId: modelIds[0],
      paperId: paperIds[0],
      foldDate: foldDates[0],
      paperType: '双面彩色',
      paperSize: '15cm x 15cm',
      durationMinutes: 6,
      rating: 5,
      notes: '第一次折叠千纸鹤，非常顺利。',
      resultImageUrl: '',
      createdAt: new Date(foldDates[0]).toISOString(),
    },
    {
      id: uuidv4(),
      modelId: modelIds[0],
      paperId: paperIds[0],
      foldDate: foldDates[2],
      paperType: '双面彩色',
      paperSize: '15cm x 15cm',
      durationMinutes: 4,
      rating: 5,
      notes: '越来越熟练了，折得更整齐。',
      resultImageUrl: '',
      createdAt: new Date(foldDates[2]).toISOString(),
    },
    {
      id: uuidv4(),
      modelId: modelIds[2],
      paperId: paperIds[2],
      foldDate: foldDates[1],
      paperType: '单面彩色',
      paperSize: '15cm x 15cm',
      durationMinutes: 5,
      rating: 4,
      notes: '跳跳蛙很有趣，但是跳得不够远。',
      resultImageUrl: '',
      createdAt: new Date(foldDates[1]).toISOString(),
    },
    {
      id: uuidv4(),
      modelId: modelIds[0],
      paperId: paperIds[0],
      foldDate: foldDates[4],
      paperType: '双面彩色',
      paperSize: '15cm x 15cm',
      durationMinutes: 3,
      rating: 5,
      notes: '已经非常熟练了，3分钟完成。',
      resultImageUrl: '',
      createdAt: new Date(foldDates[4]).toISOString(),
    },
    {
      id: uuidv4(),
      modelId: modelIds[4],
      paperId: paperIds[3],
      foldDate: foldDates[3],
      paperType: '牛皮纸',
      paperSize: '30cm x 30cm',
      durationMinutes: 20,
      rating: 4,
      notes: '折了一个大纸盒，可以放很多东西。',
      resultImageUrl: '',
      createdAt: new Date(foldDates[3]).toISOString(),
    },
    {
      id: uuidv4(),
      modelId: modelIds[1],
      paperId: paperIds[1],
      foldDate: foldDates[5],
      paperType: '和纸',
      paperSize: '20cm x 20cm',
      durationMinutes: 60,
      rating: 3,
      notes: '第一次折川崎玫瑰，花瓣部分有点难。需要多练习。',
      resultImageUrl: '',
      createdAt: new Date(foldDates[5]).toISOString(),
    },
    {
      id: uuidv4(),
      modelId: modelIds[0],
      paperId: paperIds[0],
      foldDate: foldDates[6],
      paperType: '双面彩色',
      paperSize: '15cm x 15cm',
      durationMinutes: 3,
      rating: 5,
      notes: '今天折得特别好，每一步都很精准。',
      resultImageUrl: '',
      createdAt: new Date(foldDates[6]).toISOString(),
    },
  ];
  
  db.setPaper(paperData);
  db.setModels(modelsData);
  db.setSteps(stepsData);
  db.setFolds(foldsData);
  
  console.log('Database seeded with sample data.');
}
